stages:
  - build

variables:
  DOCKER_REGISTRY: 'cr.yandex/crp9h94408osj41k4oe3'
  DOCKER_IMAGE: 'events-api'
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  image: docker:latest
  script:
    - echo $DOCKER_REGISTRY_KEY | docker login --username json_key --password-stdin cr.yandex
    - docker build -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${CI_PIPELINE_ID} .
    - docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${CI_PIPELINE_ID}

